export type ServiceIconName = "home" | "route" | "building" | "box" | "heart" | "package" | "apartment" | "squares" | "warehouse" | "sparkles" | "shield" | "trash";

export type ServicePageData = {
  slug: string;
  sourcePath: string;
  title: string;
  icon: ServiceIconName;
  sectionOneImage: string;
  sectionTwoImage: string;
  description: string;
  heroEyebrow: string;
  heroTitle: string;
  heroAccent: string;
  heroDescription: string;
  heroPoints: string[];
  sectionOneTitle: string;
  sectionOneBody: string;
  sectionTwoTitle: string;
  sectionTwoBody: string;
  whyChooseTitle: string;
  whyChooseIntro: string;
  whyChooseCards: Array<{ number: string; title: string; description: string }>;
};

export const movingSuppliesIntro = "If you don't have your own moving supplies, don't worry-we've got you covered! Simply let us know when you book, and we'll ensure our team arrives with everything you need.";
export const movingSuppliesSectionImage = "/service-images/moving-supplies-hero.jpeg";

export const movingSuppliesItems = [
  { title: "Packing Paper", price: "$20/Box", description: "Provides cushioning and protection for fragile items like glassware, artwork, and electronics." },
  { title: "Packing Blankets", price: "$15 per blanket.", description: "Thick, padded blankets designed to protect furniture and appliances from scratches and damage." },
  { title: "Ratchet Straps", price: "$5 each.", description: "Secures items in place to prevent shifting or damage during transport." },
  { title: "Plastic Wrap", price: "$30 per roll.", description: "Can be used to wrap a dresser or cabinet so the doors and drawers stay in place or fasten furniture pads to items that need to be protected." },
] as const;

export const servicePages: ServicePageData[] = [
  {
    slug: "residential-moving",
    sourcePath: "https://www.5starmoversmn.com/residential-movers",
    title: "Residential Moving",
    icon: "home",
    sectionOneImage: "/service-images/residential-1.jpeg",
    sectionTwoImage: "/service-images/residential-2.jpeg",
    description: "Safe and efficient home moves handled with family-first care.",
    heroEyebrow: "Minnesota Home Relocations",
    heroTitle: "Residential Moving",
    heroAccent: "Made Simple",
    heroDescription: "Professional home movers, transparent planning, and careful handling for houses, condos, and townhomes across Minnesota.",
    heroPoints: ["Licensed & insured crews", "Upfront quotes", "Packing to final placement"],
    sectionOneTitle: "Enjoy 5-Star Residential Moving Services for Your Home",
    sectionOneBody: "Moving can be overwhelming, but our professional residential movers make the process easy. Whether you're relocating across town or to a new city, we provide reliable moving services tailored to your needs. Our experienced team handles everything from packing and loading to transportation and unloading, ensuring your belongings arrive safely. As trusted home movers, we prioritize efficiency, care, and top-tier customer service. With transparent pricing and expert handling, we take the stress out of moving so you can focus on settling into your new home.",
    sectionTwoTitle: "We're Minnesota's Residential Movers You Can Trust",
    sectionTwoBody: "With a focus on efficiency and care, we make your move effortless from start to finish. Our residential movers bring years of experience, handling your belongings as if they were our own. Whether you're relocating across town or to a new city, we ensure a smooth and secure transition. Count on our team for top-quality service tailored to your needs.",
    whyChooseTitle: "Why Homeowners Choose Our Residential Moving Team",
    whyChooseIntro: "We shaped this section around what matters most on a home move: fewer surprises, better protection, and a crew that keeps your day calm.",
    whyChooseCards: [
      { number: "01", title: "Careful In-Home Handling", description: "From door frames to fragile furniture, our crews protect your home and your belongings at every stage." },
      { number: "02", title: "Smooth Scheduling", description: "Clear arrival windows, fast coordination, and a plan that keeps your move on pace from morning to final unload." },
      { number: "03", title: "Trusted Local Service", description: "Minnesota families rely on us for reliable communication, respectful crews, and clean execution on moving day." },
    ],
  },
  {
    slug: "long-distance-moving",
    sourcePath: "https://www.5starmoversmn.com/long-distance-moving-company",
    title: "Long Distance Moving",
    icon: "route",
    sectionOneImage: "/service-images/long-distance-1.jpg",
    sectionTwoImage: "/service-images/truck-1.jpg",
    description: "Cross-country logistics built for reliable, low-stress delivery.",
    heroEyebrow: "State To State Precision",
    heroTitle: "Long Distance Moves",
    heroAccent: "Without The Chaos",
    heroDescription: "Dedicated planning, secure transport, and consistent updates for Minnesota relocations that go beyond the local map.",
    heroPoints: ["Route planning support", "Secure loading", "Consistent delivery updates"],
    sectionOneTitle: "Enjoy a 5-Star Long Distance Moving Experience",
    sectionOneBody: "Moving far from home requires careful planning and reliable service. Our Minnesota movers specialize in seamless relocations, ensuring your belongings are packed, transported, and delivered safely. Whether you're moving from Minneapolis, St. Paul, or anywhere in Minnesota, we handle every detail with precision. From expert packing to secure loading and timely delivery, we make the process hassle-free. With our trusted team, you get transparent pricing, real-time updates, and professional service every step of the way.",
    sectionTwoTitle: "Long Distance Moving Company You Can Trust",
    sectionTwoBody: "A successful move means more than just transporting boxes-it's about peace of mind. Our long distance moving company in Minnesota takes extra measures to ensure your items arrive in perfect condition. We use high-quality packing materials, GPS-tracked trucks, and experienced movers to guarantee a smooth transition. Whether it's a residential or commercial move, we tailor our services to fit your needs, so you can focus on settling into your new home.",
    whyChooseTitle: "Why Clients Trust Us For Long Distance Relocations",
    whyChooseIntro: "Long-distance service needs stronger coordination than a local move, so these are the three things we put front and center.",
    whyChooseCards: [
      { number: "01", title: "Dedicated Move Planning", description: "We map timing, inventory, and travel details early so your move stays organized from pickup through delivery." },
      { number: "02", title: "Secure Transit Standards", description: "Protected loading, stable stacking, and careful transport reduce risk across longer mileage and tighter timelines." },
      { number: "03", title: "Clear Communication", description: "You get proactive updates and dependable contact points so you never feel out of the loop during the trip." },
    ],
  },
  {
    slug: "commercial-moving",
    sourcePath: "https://www.5starmoversmn.com/commercial-movers",
    title: "Commercial Moving",
    icon: "building",
    sectionOneImage: "/service-images/commercial-1.jpeg",
    sectionTwoImage: "/service-images/commercial-2.jpeg",
    description: "Office relocations planned to minimize downtime and disruption.",
    heroEyebrow: "Business Relocation Support",
    heroTitle: "Commercial Moving",
    heroAccent: "That Protects Productivity",
    heroDescription: "Structured office and business relocations with expert coordination, careful equipment handling, and minimal interruption.",
    heroPoints: ["After-hours options", "Office equipment care", "Downtime-conscious planning"],
    sectionOneTitle: "Enjoy a 5-Star Commercial Moving Experience",
    sectionOneBody: "A business move requires precision and efficiency, and our commercial movers in Minnesota are here to ensure a smooth transition. We specialize in office, retail, and corporate relocations, minimizing downtime and keeping your operations on track. Whether you're moving within Minneapolis, St. Paul, or anywhere in Minnesota, our experienced team handles everything from packing and furniture assembly to secure transportation. With top-rated service and expert coordination, we make business moves stress-free and efficient.",
    sectionTwoTitle: "Why Businesses Trust Our Commercial Movers in Minnesota",
    sectionTwoBody: "Choosing the right commercial movers in Minnesota is crucial for a successful relocation. We understand the importance of minimizing disruptions, so we work around your schedule to ensure a smooth transition. Our team is skilled in moving office furniture, electronics, and sensitive equipment with care. Whether you're relocating a small business or a large corporate office, we provide tailored solutions to meet your needs. With our trusted Minnesota commercial movers, you can focus on your business while we handle the heavy lifting.",
    whyChooseTitle: "Why Minnesota Businesses Move With 5-Star Movers",
    whyChooseIntro: "For commercial work, strong execution matters more than flashy promises. These are the advantages we highlight for business clients.",
    whyChooseCards: [
      { number: "01", title: "Downtime-First Planning", description: "We build around your schedule to reduce interruptions and keep teams, customers, and operations moving." },
      { number: "02", title: "Sensitive Equipment Care", description: "Office furniture, electronics, and key assets are handled with the control required for business environments." },
      { number: "03", title: "Coordinated Crew Execution", description: "Clear staging, fast loading, and organized placement help your new space come online with less friction." },
    ],
  },
  {
    slug: "loading-unloading",
    sourcePath: "https://www.5starmoversmn.com/loading-and-unloading-services",
    title: "Loading & Unloading",
    icon: "box",
    sectionOneImage: "/service-images/loading-local-1.jpeg",
    sectionTwoImage: "/service-images/loading-local-2.jpeg",
    description: "Professional labor for trucks, pods, and storage containers.",
    heroEyebrow: "Labor-Only Moving Help",
    heroTitle: "Loading & Unloading",
    heroAccent: "Done Right",
    heroDescription: "Professional labor support for rental trucks, containers, pods, and storage moves anywhere in Minnesota.",
    heroPoints: ["Labor-only support", "Safer heavy lifting", "Smarter truck packing"],
    sectionOneTitle: "Enjoy a 5-Star Loading and Unloading Experience",
    sectionOneBody: "Moving can be exhausting, but our loading and unloading services in Minnesota take the hard work off your shoulders. Whether you need help loading a rental truck, storage container, or PODS unit, our expert movers handle your belongings with care. We ensure items are properly secured for safe transport and efficiently unloaded at your destination. Serving Minneapolis, St. Paul, and surrounding areas, we provide reliable labor-only moving assistance tailored to your needs.",
    sectionTwoTitle: "We're the Loading and Unloading Experts in Minnesota",
    sectionTwoBody: "We're committed to providing top-quality loading and unloading services in Minnesota, ensuring a smooth and efficient moving experience. Our skilled movers are trained to lift, stack, and secure items safely, preventing damage and optimizing space. Whether you're moving locally or long-distance, we handle everything from heavy furniture to fragile belongings with care. Trust our Minnesota moving labor services to make your move effortless and stress-free.",
    whyChooseTitle: "Why Clients Book Us For Labor-Only Moves",
    whyChooseIntro: "This service wins when the crew is efficient, careful, and strategic about how space gets used. That is exactly how we positioned it.",
    whyChooseCards: [
      { number: "01", title: "Efficient Load Strategy", description: "We stack and secure items with purpose so trucks and containers stay balanced, protected, and better organized." },
      { number: "02", title: "Heavy Item Confidence", description: "Bulky furniture, appliances, and awkward pieces are handled by trained movers instead of guesswork and strain." },
      { number: "03", title: "Flexible Support", description: "Perfect for pods, storage units, and rental trucks when you need muscle and technique without a full-service move." },
    ],
  },
  {
    slug: "senior-moving",
    sourcePath: "https://www.5starmoversmn.com/senior-movers",
    title: "Senior Moving",
    icon: "heart",
    sectionOneImage: "/service-images/senior-1.jpeg",
    sectionTwoImage: "/service-images/senior-2.jpeg",
    description: "Compassionate service tailored for transitions that need extra care.",
    heroEyebrow: "Gentle Relocation Support",
    heroTitle: "Senior Moving",
    heroAccent: "With More Care",
    heroDescription: "Thoughtful moving help for downsizing, assisted living transitions, and family-supported relocations across Minnesota.",
    heroPoints: ["Patient crews", "Family-friendly communication", "Setup assistance"],
    sectionOneTitle: "Enjoy a 5-Star Senior Moving Experience",
    sectionOneBody: "Relocating in your golden years should be smooth and worry-free. Our senior movers in Minnesota specialize in providing gentle, efficient, and thoughtful moving services for older adults. Whether downsizing, transitioning to assisted living, or moving closer to family, we handle every detail with care. We assist with packing, loading, transportation, and setup, ensuring a seamless experience for you and your loved ones. With trusted senior moving services, we make moving easier and more comfortable for seniors in Minneapolis, St. Paul, and beyond.",
    sectionTwoTitle: "We're the Senior Movers Minnesota Trusts",
    sectionTwoBody: "We're dedicated to making senior moves stress-free and handled with care. Our Minnesota senior movers understand the unique challenges of relocating later in life and provide personalized support every step of the way. From carefully packing cherished belongings to setting up your new home just the way you like it, we take the time to ensure a comfortable transition. Our goal is to make moving simple, safe, and reassuring for seniors and their families.",
    whyChooseTitle: "Why Families Trust Our Senior Moving Process",
    whyChooseIntro: "Senior relocations need patience and reassurance, so this section speaks to emotional comfort as much as logistics.",
    whyChooseCards: [
      { number: "01", title: "Compassionate Pace", description: "We move with patience and respect, helping older adults feel comfortable instead of rushed throughout the transition." },
      { number: "02", title: "Family-Ready Communication", description: "Clear updates make it easier for relatives, caregivers, and decision-makers to stay informed and aligned." },
      { number: "03", title: "Thoughtful Setup Help", description: "We do more than deliver boxes-we help create a smoother landing in the next home or community." },
    ],
  },
  {
    slug: "packing-services",
    sourcePath: "https://www.5starmoversmn.com/packing-services",
    title: "Packing Services",
    icon: "package",
    sectionOneImage: "/service-images/packing-1.jpg",
    sectionTwoImage: "/service-images/packing-2.jpeg",
    description: "Full-service wrapping and packing for fragile, valuable items.",
    heroEyebrow: "Professional Protection",
    heroTitle: "Packing Services",
    heroAccent: "That Save Time",
    heroDescription: "Full packing, fragile-only support, and organized prep work that makes your move safer and easier from day one.",
    heroPoints: ["Fragile-item expertise", "High-quality materials", "Organized labeling"],
    sectionOneTitle: "Enjoy 5-Star Packing Services for a Hassle-Free Move",
    sectionOneBody: "Packing is one of the most time-consuming parts of moving, but our packing services in Minnesota make it effortless. Whether you need full-service packing, fragile item protection, or specialized packing for valuables, we have the expertise to keep your belongings safe. Our professional team uses high-quality materials and proven techniques to ensure everything is secure for transport. Serving Minneapolis, St. Paul, and surrounding areas, we take the stress out of packing so you can focus on your move.",
    sectionTwoTitle: "We're the Packing Experts in Minnesota",
    sectionTwoBody: "We're committed to providing top-tier packing services in Minnesota, ensuring every item is handled with care. Our team customizes packing solutions based on your needs, whether for a residential move, commercial relocation, or specialty items like antiques and electronics. From careful wrapping to organized labeling, we make unpacking just as easy as packing. Let our Minnesota packing specialists simplify your move with professional and efficient service.",
    whyChooseTitle: "Why Clients Upgrade To Professional Packing",
    whyChooseIntro: "Packing is where moves are often won or lost. These three points push the value clearly without drifting from the brand language.",
    whyChooseCards: [
      { number: "01", title: "Material Selection", description: "We use the right wraps, paper, and padding for each item instead of a one-size-fits-all packing approach." },
      { number: "02", title: "Fragile Item Protection", description: "Glassware, artwork, electronics, and valuables are packed with methods built for safer transport." },
      { number: "03", title: "Cleaner Unpacking", description: "Organized labeling and room-by-room prep make delivery day feel far more controlled and manageable." },
    ],
  },
  {
    slug: "apartment-moving",
    sourcePath: "https://www.5starmoversmn.com/apartment-movers",
    title: "Apartment Moving",
    icon: "apartment",
    sectionOneImage: "/service-images/apartment-1.jpeg",
    sectionTwoImage: "/service-images/apartment-2.jpeg",
    description: "Tight stairs, elevators, and city access handled with precision.",
    heroEyebrow: "Urban Move Specialists",
    heroTitle: "Apartment Moving",
    heroAccent: "Without The Friction",
    heroDescription: "Fast, efficient apartment relocations built for stairs, elevators, parking limits, and high-density city moves.",
    heroPoints: ["Building logistics", "Tight-space maneuvering", "Fast truck turnaround"],
    sectionOneTitle: "Enjoy a 5-Star Apartment Moving Experience",
    sectionOneBody: "Moving into a new apartment comes with unique challenges, from navigating stairs to coordinating with building management. Our apartment movers in Minnesota specialize in smooth, stress-free moves for renters and homeowners alike. Whether you're moving into a high-rise in Minneapolis, a condo in St. Paul, or anywhere in Minnesota, we ensure a seamless transition. From carefully packing and loading to maneuvering tight spaces, we handle everything with care and efficiency.",
    sectionTwoTitle: "We're the Apartment Movers Minnesota Trusts",
    sectionTwoBody: "We're committed to making apartment moves effortless. Our Minnesota apartment movers understand the logistics of multi-story buildings, elevators, and parking restrictions. We offer tailored moving solutions that fit your needs, whether you're relocating a studio or a multi-bedroom unit. With our professional team handling the heavy lifting, you can enjoy a stress-free moving experience.",
    whyChooseTitle: "Why Apartment Moves Run Better With 5-Star Movers",
    whyChooseIntro: "Apartment jobs have tighter constraints, so this section focuses on speed, access, and planning around building rules.",
    whyChooseCards: [
      { number: "01", title: "Building-Ready Planning", description: "We account for elevator schedules, access points, and parking limitations before moving day starts." },
      { number: "02", title: "Tight-Space Handling", description: "Stairs, hallways, corners, and compact entryways are handled with more control and less stress." },
      { number: "03", title: "Efficient City Execution", description: "Fast loading and organized crew flow help keep apartment relocations moving even in dense urban settings." },
    ],
  },
  {
    slug: "moving-supplies",
    sourcePath: "https://www.5starmoversmn.com/moving-supplies",
    title: "Moving Supplies",
    icon: "squares",
    sectionOneImage: "/service-images/moving-supplies-1.jpeg",
    sectionTwoImage: "/service-images/packing-1.jpg",
    description: "Premium boxes, wraps, and protection delivered when you need them.",
    heroEyebrow: "Packing Materials On Demand",
    heroTitle: "Moving Supplies",
    heroAccent: "Ready When You Are",
    heroDescription: "Get the essential packing materials your move needs, backed by the same 5-Star guidance and service approach.",
    heroPoints: ["Boxes and wraps available", "Add supplies to your booking", "Protection for fragile items"],
    sectionOneTitle: "Enjoy 5-Star Moving Supplies for a Secure Move",
    sectionOneBody: "Having the right packing materials is key to a successful move. Our moving supplies in Minnesota include durable boxes, packing tape, bubble wrap, and specialty packing materials to keep your items safe during transit. Whether you're moving locally or long-distance, we provide high-quality materials designed for every packing need. Serving Minneapolis, St. Paul, and beyond, we make sure you have everything required for a stress-free move.",
    sectionTwoTitle: "Get the Best Moving Supplies in Minnesota",
    sectionTwoBody: "We provide high-quality moving supplies to ensure your belongings are protected and secured for any move. Whether you need durable boxes, bubble wrap, or packing tape, our supplies are designed to keep everything safe from start to finish.",
    whyChooseTitle: "Why Customers Add Supplies Through 5-Star Movers",
    whyChooseIntro: "This page needs to sell confidence and convenience, so the value proposition is simple and practical.",
    whyChooseCards: [
      { number: "01", title: "Pro-Grade Materials", description: "Use supplies designed for real moving conditions, not improvised packaging that creates extra risk." },
      { number: "02", title: "Smarter Recommendations", description: "We help match wraps, blankets, and protection materials to the types of items you are actually moving." },
      { number: "03", title: "Convenient Add-On", description: "Supplies can be coordinated with your move so you spend less time sourcing materials from multiple places." },
    ],
  },
  {
    slug: "storage",
    sourcePath: "https://www.5starmoversmn.com/storage-solutions",
    title: "Storage",
    icon: "warehouse",
    sectionOneImage: "/service-images/storage-1.jpeg",
    sectionTwoImage: "/service-images/truck-1.jpg",
    description: "Secure short and long-term storage options that stay easy to access.",
    heroEyebrow: "Flexible Storage Support",
    heroTitle: "Storage Solutions",
    heroAccent: "Built Around Your Timeline",
    heroDescription: "Short-term and long-term storage options that keep your belongings secure, accessible, and move-ready.",
    heroPoints: ["Short and long-term options", "Secure facilities", "Easy coordination with your move"],
    sectionOneTitle: "Enjoy 5-Star Storage Solutions for Your Peace of Mind",
    sectionOneBody: "Whether you need short-term storage during a move or long-term space for extra belongings, our storage solutions in Minnesota offer security and convenience. We provide climate-controlled storage, secure facilities, and easy access to keep your items protected. Serving Minneapolis, St. Paul, and beyond, our storage services are designed to fit your needs, ensuring your belongings remain safe until you're ready for them.",
    sectionTwoTitle: "We're the Storage Experts in Minnesota",
    sectionTwoBody: "We're committed to providing the most reliable storage solutions in Minnesota with flexible options tailored to you. Whether you're downsizing, renovating, or in need of extra space, we have the perfect storage solution. Our facilities are monitored, well-maintained, and easily accessible when you need your items. Trust our Minnesota storage experts to keep your belongings safe and secure.",
    whyChooseTitle: "Why Clients Use Our Storage Options During A Move",
    whyChooseIntro: "Storage works best when it removes pressure from the timeline, so these cards focus on flexibility, security, and convenience.",
    whyChooseCards: [
      { number: "01", title: "Flexible Timing", description: "Ideal for delayed closings, phased moves, renovations, and any schedule that does not line up perfectly." },
      { number: "02", title: "Secure Holding", description: "Your belongings stay in monitored, well-maintained spaces designed to protect them while plans shift." },
      { number: "03", title: "Move Coordination", description: "Because storage and moving are connected, retrieval and delivery stay easier to manage when you are ready." },
    ],
  },
  {
    slug: "white-glove-moving",
    sourcePath: "https://www.5starmoversmn.com/white-glove-movers",
    title: "White Glove Moving",
    icon: "sparkles",
    sectionOneImage: "/service-images/residential-2.jpeg",
    sectionTwoImage: "/service-images/residential-3.jpeg",
    description: "Luxury-level care for valuables, artwork, and specialty pieces.",
    heroEyebrow: "Premium Handling",
    heroTitle: "White Glove Moving",
    heroAccent: "For High-Value Items",
    heroDescription: "Detail-oriented moving for designer furniture, antiques, art, electronics, and other pieces that need premium care.",
    heroPoints: ["High-value item handling", "Custom protection", "Premium delivery experience"],
    sectionOneTitle: "Enjoy a 5-Star White Glove Moving Experience",
    sectionOneBody: "Luxury moves require precision, care, and expertise. Our white glove movers in Minnesota specialize in handling high-value, delicate, and specialty items with meticulous attention. From antiques and fine art to designer furniture and electronics, we ensure every item is professionally packed, transported, and delivered safely. Whether you're moving a high-end residence or need specialized handling, our team guarantees a smooth, damage-free experience.",
    sectionTwoTitle: "We're the White Glove Movers Minnesota Trusts",
    sectionTwoBody: "We're committed to offering unparalleled white glove moving services in Minnesota, ensuring your most valuable possessions receive the highest level of care. Our professional team is trained in specialized packing techniques, custom crating, and careful transport to maintain the integrity of your belongings. Whether relocating locally or long-distance, our Minnesota white glove movers handle every detail with precision and professionalism.",
    whyChooseTitle: "Why Clients Choose White Glove Service",
    whyChooseIntro: "This service is about reassurance and precision, so the supporting points stay elevated but still practical.",
    whyChooseCards: [
      { number: "01", title: "Premium Item Protection", description: "Delicate and high-value pieces receive the kind of packing and handling standards standard moves do not require." },
      { number: "02", title: "Custom Care Methods", description: "From specialty wrapping to crating plans, we adapt the process to the item instead of forcing a generic workflow." },
      { number: "03", title: "Detail-Oriented Delivery", description: "Every stage is executed with a more controlled, polished service experience designed for premium possessions." },
    ],
  },
  {
    slug: "specialty-moving",
    sourcePath: "https://www.5starmoversmn.com/specialty-moving-company",
    title: "Specialty Moving",
    icon: "shield",
    sectionOneImage: "/service-images/residential-3.jpeg",
    sectionTwoImage: "/service-images/truck-1.jpg",
    description: "Pianos, safes, antiques, and oversized items moved by experts.",
    heroEyebrow: "Complex Item Transport",
    heroTitle: "Specialty Moving",
    heroAccent: "Handled With Precision",
    heroDescription: "Expert relocation support for pianos, antiques, appliances, fine art, and oversized items that need more than standard moving.",
    heroPoints: ["Oversized-item expertise", "Custom crating options", "Precision handling"],
    sectionOneTitle: "Enjoy a 5-Star Specialty Moving Experience",
    sectionOneBody: "Some items require extra care, and our specialty moving company in Minnesota is equipped to handle even the most complex relocations. Whether you need to move a piano, fine art, antiques, or large appliances, we use specialized packing, secure transport, and expert techniques to ensure safe delivery. Serving Minneapolis, St. Paul, and beyond, we provide customized moving solutions for your most valuable possessions.",
    sectionTwoTitle: "We're the Specialty Moving Company Minnesota Trusts",
    sectionTwoBody: "We're dedicated to providing reliable specialty moving services in Minnesota with the highest level of care and precision. Our expert movers are trained to handle fragile and heavy items, offering custom crating, climate-controlled transport, and meticulous handling. Whether you're relocating unique household items or specialty business equipment, our Minnesota specialty movers ensure a seamless and stress-free experience.",
    whyChooseTitle: "Why Specialty Items Need A Specialty Crew",
    whyChooseIntro: "Oversized and delicate items create different risks, so this section leans into expertise, tools, and control.",
    whyChooseCards: [
      { number: "01", title: "Complex Item Experience", description: "We are prepared for fragile, heavy, oversized, and awkward pieces that demand more planning and technique." },
      { number: "02", title: "Custom Protection Options", description: "Crating, specialty wraps, and tailored transport methods help reduce damage risk on unique pieces." },
      { number: "03", title: "Precision From Start To Finish", description: "From pickup paths to final placement, the process stays controlled so your most difficult items move safely." },
    ],
  },
  {
    slug: "junk-removal",
    sourcePath: "https://www.5starmoversmn.com/junk-removal-service",
    title: "Junk Removal",
    icon: "trash",
    sectionOneImage: "/service-images/loading-local-2.jpeg",
    sectionTwoImage: "/service-images/storage-1.jpeg",
    description: "Declutter before or after the move without adding extra stress.",
    heroEyebrow: "Fast Clear-Out Support",
    heroTitle: "Junk Removal",
    heroAccent: "Without The Headache",
    heroDescription: "Remove unwanted furniture, appliances, debris, and clutter quickly with a team that can pair it with your move.",
    heroPoints: ["Fast pick-up", "Responsible disposal", "Useful before or after a move"],
    sectionOneTitle: "Enjoy a 5-Star Junk Removal Experience",
    sectionOneBody: "Decluttering your space has never been easier. Our junk removal service in Minnesota helps homeowners and businesses clear unwanted items quickly and responsibly. Whether you're removing old furniture, appliances, construction debris, or general clutter, our team ensures efficient pickup and proper disposal. Serving Minneapolis, St. Paul, and beyond, we handle the heavy lifting so you don't have to.",
    sectionTwoTitle: "We're the Junk Removal Experts Minnesota Trusts",
    sectionTwoBody: "We're committed to providing hassle-free junk removal services in Minnesota that are fast, reliable, and environmentally responsible. Our team ensures proper disposal, recycling, and donation of items whenever possible. Whether you're cleaning out a home, office, or storage unit, our Minnesota junk removal experts make the process seamless and stress-free.",
    whyChooseTitle: "Why Customers Add Junk Removal To Their Move",
    whyChooseIntro: "This service performs best when it feels easy and responsible, so the supporting points are built around speed and convenience.",
    whyChooseCards: [
      { number: "01", title: "Quick Clear-Outs", description: "We help remove clutter efficiently so homes, apartments, offices, and storage units can be reset faster." },
      { number: "02", title: "Responsible Disposal", description: "Whenever possible, we prioritize proper disposal, recycling, and donation instead of a careless dump-and-go approach." },
      { number: "03", title: "Move-Day Convenience", description: "It is an easy add-on before listing a home, before packing, or after delivery when you need the extras gone." },
    ],
  },
];

export const servicePageMap = Object.fromEntries(servicePages.map((service) => [service.slug, service])) as Record<string, ServicePageData>;
